### ISSUE TITLE
Error or something when a player leaves the server

### ISSUE THREAD

**Issue by TrevorBagels** [henkelmax/persistent-players#2]
**Please read the [FAQ](https://modrepo.de/minecraft/persistent_players/faq) before submitting a bug report!**

**Bug description**
Whenever I log off the server, the console prints this out:
```
[08:04:38] [Server thread/INFO] [minecraft/NetHandlerPlayServer]: theangrybagel lost connection: Disconnected
[08:04:38] [Server thread/INFO] [minecraft/DedicatedServer]: theangrybagel left the game
[08:04:38] [Server thread/INFO] [warpdrive]: Skipping offline avatar for off board player EntityPlayerMP['theangrybagel'/15, l='BZOverworld', x=166.49, y=65.00, z=325.93]
[08:04:38] [Server thread/INFO] [STDERR]: [de.maxhenkel.persistentplayers.entities.PersistentPlayerEntity:fromPlayer:74]: net.minecraftforge.fml.relauncher.ReflectionHelper$UnableToFindFieldException: java.lang.NoSuchFieldException: fire
[08:04:38] [Server thread/INFO] [STDERR]: [de.maxhenkel.persistentplayers.entities.PersistentPlayerEntity:fromPlayer:74]: 	at net.minecraftforge.fml.relauncher.ReflectionHelper.findField(ReflectionHelper.java:166)
[08:04:38] [Server thread/INFO] [STDERR]: [de.maxhenkel.persistentplayers.entities.PersistentPlayerEntity:fromPlayer:74]: 	at net.minecraftforge.fml.common.ObfuscationReflectionHelper.findField(ObfuscationReflectionHelper.java:161)
[08:04:38] [Server thread/INFO] [STDERR]: [de.maxhenkel.persistentplayers.entities.PersistentPlayerEntity:fromPlayer:74]: 	at de.maxhenkel.persistentplayers.entities.PersistentPlayerEntity.fromPlayer(PersistentPlayerEntity.java:71)
[08:04:38] [Server thread/INFO] [STDERR]: [de.maxhenkel.persistentplayers.entities.PersistentPlayerEntity:fromPlayer:74]: 	at de.maxhenkel.persistentplayers.events.PlayerEvents.playerLogOut(PlayerEvents.java:60)
[08:04:38] [Server thread/INFO] [STDERR]: [de.maxhenkel.persistentplayers.entities.PersistentPlayerEntity:fromPlayer:74]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1914_PlayerEvents_playerLogOut_PlayerLoggedOutEvent.invoke(.dynamic)
[08:04:38] [Server thread/INFO] [STDERR]: [de.maxhenkel.persistentplayers.entities.PersistentPlayerEntity:fromPlayer:74]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
[08:04:38] [Server thread/INFO] [STDERR]: [de.maxhenkel.persistentplayers.entities.PersistentPlayerEntity:fromPlayer:74]: 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
[08:04:38] [Server thread/INFO] [STDERR]: [de.maxhenkel.persistentplayers.entities.PersistentPlayerEntity:fromPlayer:74]: 	at net.minecraftforge.fml.common.FMLCommonHandler.firePlayerLoggedOut(FMLCommonHandler.java:580)
[08:04:38] [Server thread/INFO] [STDERR]: [de.maxhenkel.persistentplayers.entities.PersistentPlayerEntity:fromPlayer:74]: 	at net.minecraft.server.management.PlayerList.func_72367_e(PlayerList.java:388)
[08:04:38] [Server thread/INFO] [STDERR]: [de.maxhenkel.persistentplayers.entities.PersistentPlayerEntity:fromPlayer:74]: 	at net.minecraft.network.NetHandlerPlayServer.func_147231_a(NetHandlerPlayServer.java:853)
[08:04:38] [Server thread/INFO] [STDERR]: [de.maxhenkel.persistentplayers.entities.PersistentPlayerEntity:fromPlayer:74]: 	at net.minecraft.network.NetworkManager.func_179293_l(NetworkManager.java:457)
[08:04:38] [Server thread/INFO] [STDERR]: [de.maxhenkel.persistentplayers.entities.PersistentPlayerEntity:fromPlayer:74]: 	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:213)
[08:04:38] [Server thread/INFO] [STDERR]: [de.maxhenkel.persistentplayers.entities.PersistentPlayerEntity:fromPlayer:74]: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790)
[08:04:38] [Server thread/INFO] [STDERR]: [de.maxhenkel.persistentplayers.entities.PersistentPlayerEntity:fromPlayer:74]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
[08:04:38] [Server thread/INFO] [STDERR]: [de.maxhenkel.persistentplayers.entities.PersistentPlayerEntity:fromPlayer:74]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
[08:04:38] [Server thread/INFO] [STDERR]: [de.maxhenkel.persistentplayers.entities.PersistentPlayerEntity:fromPlayer:74]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
[08:04:38] [Server thread/INFO] [STDERR]: [de.maxhenkel.persistentplayers.entities.PersistentPlayerEntity:fromPlayer:74]: 	at java.lang.Thread.run(Thread.java:748)
[08:04:38] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]: Caused by: java.lang.NoSuchFieldException: fire
[08:04:38] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]: 	at java.lang.Class.getDeclaredField(Class.java:2070)
[08:04:38] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]: 	at net.minecraftforge.fml.relauncher.ReflectionHelper.findField(ReflectionHelper.java:160)
[08:04:38] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]: 	... 16 more
```

**Steps to reproduce the issue**
Host a server, probably with the same mods as this one
Join, then disconnect.

**Expected behavior**
That error will pop up.

**Log files**

**Versions**
Forge 1.12.2-14.23.5.2854
Minecraft 1.12.2

I'm not sure if this is a serious issue, as it doesn't seem to affect playing the game, but if I notice anything else I'll put more effort into providing the logs and modslist. (or if you think it's a rather serious issue, let me know and I'll post the log file and a modlist)

**Comment by henkelmax** [comment]
This should be fixed in 1.12.2-1.0.2
